import Head from "next/head";
// import Image from "next/image";
// import { Inter } from "next/font/google";
// import styles from "../styles/Home.module.css";
import Link from "next/link";
import { useRouter } from "next/router";
// const inter = Inter({ subsets: ["latin"] });
import { GetStaticPropsContext } from "next";
import React, { useContext, useState } from "react";
import KomaWebContext from "@/store";

// interface Props {
//   current: string;

//   // datalist: { name: string; stars: number }[];
// }

export default function Home() {
  // const { current } = props;

  const router = useRouter();

  const komWebCtx = useContext(KomaWebContext);

  const [username, setUsername] = useState("Koma");

  const txtUsername_onchange = (event: React.ChangeEvent<HTMLInputElement>) => {
   console.log(event.target.value)
    setUsername(event.target.value);
  };

  const btn_login_onclick = () => {
    komWebCtx.login(username);
    router.push({
      pathname: "/admin",
    });
  };

  // const btn_click = () => {
  //   router.push({ pathname: "/news/[id]", query: { id: "001" } });
  // };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="fs-1 p-3">
        <h1>主題頁</h1>
        <hr />
        狀態：{komWebCtx && komWebCtx.isLogin.toString()}
        <hr />
        <div className="mb-3 col-6">
          <label htmlFor="txtUsername" className="form-label">
            用戶名：
          </label>
          <input
            type="text"
            className="form-control"
            id="txtUsername"
            value={username}
            onChange={txtUsername_onchange}
          />
        </div>
        <button
          className="btn btn-success btn-lg"
          onClick={() => btn_login_onclick()}
        >
          登入
        </button>
      </div>
      <hr />
      <h1>Next.js</h1>
      <hr />
      {/* <div className="fs-1 p-3">現在的時間是：{current}</div> */}
      {/* <div className="fs-1 p-3">
        <ul>
          {datalist.map((item) => (
            <li key={item.name}>
              {item.name}:<small className="text-danger">{item.stars}</small>
            </li>
          ))}
        </ul>
      </div> */}
      <hr />
      <Link href={"/about"}>About</Link>
      <hr />
      <Link href={{ pathname: "news/[id]", query: { id: "001" } }}>
        新聞001
      </Link>
      <Link href={{ pathname: "news/[id]", query: { id: "002" } }}>
        新聞002
      </Link>
      <Link href={{ pathname: "news/[id]", query: { id: "003" } }}>
        新聞003
      </Link>
      <hr />
      {/* <button className="btn btn-success" onClick={btn_click}>
        新聞001
      </button> */}
      <hr />
      <div
        className="btn-group"
        role="group"
        aria-label="Basic mixed styles example"
      >
        <button type="button" className="btn btn-danger">
          Left
        </button>
        <button type="button" className="btn btn-warning">
          Middle
        </button>
        <button type="button" className="btn btn-success">
          Right
        </button>
      </div>
      <ul className="list-group">
        <li className="list-group-item">An item</li>
        <li className="list-group-item">A second item</li>
        <li className="list-group-item">A third item</li>
        <li className="list-group-item">A fourth item</li>
        <li className="list-group-item">And a fifth one</li>
      </ul>
    </>
  );
}

export async function getStaticProps(context: GetStaticPropsContext) {
  console.log("getStaticProps is running...");
  const date = new Date();

  var h = date.getHours();
  var m = date.getMinutes();
  var s = date.getSeconds();

  const current = h + ":" + m + ":" + s;
  return {
    props: {
      current,
    },
    revalidate: 10,
  };
}

// export async function getStaticProps(context: GetStaticPropsContext) {
//   console.log("getStaticProps is running...");
//   let res = await fetch("https://api.github.com/repos/facebook/react");
//   let json = await res.json();
//   let stars_react = json.stargazers_count;

//   res = await fetch("https://api.github.com/repos/vuejs/vue");
//   json = await res.json();
//   let stars_vue = json.stargazers_count;

//   res = await fetch("https://api.github.com/repos/angular/angular");
//   json = await res.json();
//   let stars_angular = json.stargazers_count;

//   return {
//     props: {
//       datalist: [
//         { name: "React", stars: stars_react },
//         { name: "Vue", stars: stars_vue },
//         { name: "Angular", stars: stars_angular },
//       ],
//     },
//   };
// }
